# SIEM ClickHouse Search Service Configuration
# High-performance log search with multi-tenant support

[server]
# HTTP server configuration
host = "0.0.0.0"              # Server bind address
port = 8084                    # Server port (different from main SIEM to avoid conflicts)
request_timeout_secs = 30      # Request timeout in seconds
max_request_size = 10485760    # Maximum request size in bytes (10MB)
enable_cors = true             # Enable CORS
cors_origins = ["*"]           # Allowed CORS origins

[clickhouse]
# ClickHouse database configuration
url = "http://localhost:8123"   # ClickHouse HTTP interface URL
database = "dev"               # Database name (changed to connect to existing dev.events table)
username = "default"           # Username
password = ""                  # Password (empty for default)

# Connection pool configuration
[clickhouse.pool]
max_size = 20                  # Maximum number of connections in the pool
min_idle = 5                   # Minimum number of connections to maintain
connection_timeout_secs = 30   # Connection timeout in seconds
max_lifetime_secs = 3600       # Maximum lifetime of a connection in seconds
idle_timeout_secs = 600        # Idle timeout for connections in seconds
health_check_interval_secs = 60 # Health check interval in seconds

# Query configuration
[clickhouse.query]
default_timeout_secs = 60      # Default query timeout in seconds
max_timeout_secs = 300         # Maximum query timeout in seconds
default_page_size = 100        # Default page size for search results
max_page_size = 1000           # Maximum page size allowed
max_concurrent_queries_per_tenant = 10 # Maximum concurrent queries per tenant
enable_caching = true          # Enable query result caching
cache_ttl_secs = 300           # Cache TTL in seconds
max_memory_usage = 10000000000 # Maximum memory usage per query (10GB)
enable_optimization = true     # Enable query optimization

# Table configuration
[clickhouse.tables]
default_table = "events"       # Use existing events table
tenant_table_pattern = "events_{tenant_id}" # Pattern for tenant-specific tables
auto_create_tables = false     # Don't create tables, use existing dev.events

# Partition configuration
[clickhouse.tables.partition]
time_interval = "monthly"      # Monthly partitioning
retention_days = 90           # 90 days retention
auto_prune = true             # Enable automatic pruning

# ClickHouse performance tuning section removed - not defined in ClickHouseConfig struct

[security]
# Security and authentication configuration
enable_tenant_isolation = true                    # Enable multi-tenant isolation
jwt_secret = "your-super-secret-jwt-key-here-change-this-in-production" # JWT signing secret (min 32 chars)
token_expiration_secs = 3600                      # JWT token expiration (1 hour)
enable_rate_limiting = true                       # Enable rate limiting
rate_limit_per_tenant = 1000                      # Requests per minute per tenant
enable_audit_logging = true                       # Enable audit logging
allowed_tenants = []                              # Allowed tenant IDs (empty = all allowed)

# Additional security settings removed - not defined in SecurityConfig struct

[search]
# Search behavior configuration
enable_fulltext = true                            # Enable full-text search
enable_regex = true                               # Enable regex search
max_regex_complexity = 1000                       # Maximum regex complexity score
enable_streaming = true                           # Enable search result streaming
streaming_chunk_size = 1000                       # Streaming chunk size
enable_analytics = true                           # Enable search analytics
ranking_algorithm = "relevance"                   # Search result ranking algorithm
enable_suggestions = true                         # Enable search suggestions

# Search performance and fulltext subsections removed - not defined in SearchConfig struct

[redis]
# Redis configuration for caching
url = "redis://localhost:6379/1"  # Redis connection URL
pool_size = 20                     # Connection pool size
connection_timeout_secs = 5        # Connection timeout in seconds
default_ttl_secs = 3600           # Default TTL for cached items in seconds
max_cache_size = 1073741824       # Maximum cache size in bytes (1GB)
enable_compression = true          # Enable cache compression

# Redis clustering subsection removed - not defined in RedisConfig struct

[monitoring]
# Monitoring and observability
enable_metrics = true                    # Enable Prometheus metrics
metrics_path = "/metrics"                # Metrics endpoint path
enable_health_check = true               # Enable health check endpoint
health_check_path = "/health"            # Health check endpoint path
enable_performance_monitoring = true     # Enable performance monitoring
performance_interval_secs = 60           # Performance metrics collection interval in seconds
enable_query_logging = true              # Enable query logging
slow_query_threshold_ms = 5000           # Log slow queries threshold in milliseconds

# Metrics collection intervals subsection removed - not defined in MonitoringConfig struct

# Retention section removed - retention is configured in [clickhouse.tables.partition]

# Detection section removed - not defined in Config struct

# API and features sections removed - not defined in Config struct

# Configuration file cleaned - only sections defined in Config struct remain