# Pre-commit hooks configuration for API contract validation
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: local
    hooks:
      - id: api-contract-validation
        name: API Contract Validation
        entry: ./scripts/validate-api-contract.sh
        language: script
        files: '^(openapi\.json|siem_ui/src/(services/typedApi\.ts|hooks/api/useTypedLogSources\.ts|generated/api-types\.ts)|siem_ui/scripts/generate-api-client\.cjs)$'
        pass_filenames: false
        verbose: true
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        files: '^openapi\.json$'
        
      - id: check-yaml
        files: '\.(yml|yaml)$'
        
      - id: trailing-whitespace
        files: '^(openapi\.json|siem_ui/src/.*\.(ts|tsx|js|jsx))$'
        
      - id: end-of-file-fixer
        files: '^(openapi\.json|siem_ui/src/.*\.(ts|tsx|js|jsx))$'
        
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: '\.py$'
        
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: '^siem_ui/src/.*\.(ts|tsx|js|jsx)$'
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'
          - 'eslint@^8.0.0'
        args: ['--fix', '--max-warnings=0']
        
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '^siem_ui/src/.*\.(ts|tsx|js|jsx|json|css|scss|md)$'
        additional_dependencies:
          - 'prettier@^3.0.0'
        
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
    
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false