# SIEM Ingestion Pipeline Configuration
# Production-grade configuration with all available options

# Core ingestion settings
ingestion:
  # Processing limits
  max_events_per_file: 50000
  max_events_per_dataset: 100000
  batch_size: 1000
  
  # Feature toggles
  enable_format_detection: true
  enable_validation: true
  enable_metrics: true
  enable_retry: true
  continue_on_parse_errors: true
  
  # Logging configuration
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  structured_logging: true
  log_file: "/var/log/siem/ingestion.log"
  
  # Data validation
  required_fields:
    - "timestamp"
    - "event_type"
  
  optional_fields:
    - "source_ip"
    - "destination_ip"
    - "user_name"
    - "process_name"
  
  # Field transformations
  field_mappings:
    "@timestamp": "timestamp"
    "event.action": "event_type"
    "source.ip": "source_ip"
    "destination.ip": "destination_ip"
    "user.name": "user_name"
    "process.name": "process_name"
  
  # Retry configuration
  retry:
    max_attempts: 3
    initial_delay: 1.0
    max_delay: 60.0
    exponential_base: 2
    jitter: true
  
  # Performance tuning
  performance:
    worker_threads: 4
    memory_limit_mb: 2048
    temp_dir: "/tmp/siem_ingestion"
    cleanup_temp_files: true

# SIEM API configuration
siem:
  api_url: "http://localhost:8080"
  timeout: 30
  max_retries: 3
  
  # Authentication
  auth:
    type: "bearer"  # bearer, basic, api_key
    token: "${SIEM_API_TOKEN}"
  
  # Endpoints
  endpoints:
    events: "/api/v1/events"
    health: "/api/v1/health"
    metrics: "/api/v1/metrics"

# Monitoring and observability
monitoring:
  # Prometheus metrics
  prometheus:
    enabled: true
    port: 9090
    host: "0.0.0.0"
    metrics_path: "/metrics"
  
  # Health checks
  health_check:
    enabled: true
    interval: 30
    timeout: 10
    endpoints:
      - "${SIEM_API_URL}/health"
      - "http://clickhouse:8123/ping"
  
  # Alerting thresholds
  alerts:
    error_rate_threshold: 0.05  # 5%
    processing_latency_threshold: 300  # 5 minutes
    memory_usage_threshold: 0.85  # 85%
    disk_usage_threshold: 0.90  # 90%

# Data sources configuration
data_sources:
  # OTRF Security Datasets
  otrf:
    enabled: true
    base_path: "/data/Security-Datasets"
    categories:
      - "windows"
      - "linux"
      - "macos"
    
    # Dataset filtering
    filters:
      min_size_mb: 1
      max_size_mb: 1000
      exclude_patterns:
        - "*test*"
        - "*sample*"
  
  # Custom datasets
  custom:
    enabled: true
    paths:
      - "/data/custom_logs"
      - "/data/threat_intel"
    
    # File patterns
    patterns:
      - "*.json"
      - "*.jsonl"
      - "*.ndjson"
      - "*.zip"
      - "*.gz"

# Multi-tenant configuration
tenants:
  default:
    name: "Default Tenant"
    enabled: true
    data_retention_days: 90
    max_events_per_day: 1000000
  
  tenant_a:
    name: "Tenant A - Production"
    enabled: true
    data_retention_days: 365
    max_events_per_day: 5000000
    priority: "high"
  
  tenant_b:
    name: "Tenant B - Development"
    enabled: true
    data_retention_days: 30
    max_events_per_day: 100000
    priority: "low"

# Security settings
security:
  # Data encryption
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
  
  # Access control
  access_control:
    enabled: true
    allowed_ips:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst_size: 100
  
  # Audit logging
  audit:
    enabled: true
    log_file: "/var/log/siem/audit.log"
    include_data_samples: false

# Development and testing
development:
  # Debug settings
  debug:
    enabled: false
    profile_performance: false
    save_intermediate_files: false
    verbose_errors: true
  
  # Test data generation
  test_data:
    enabled: false
    generate_events: 1000
    event_rate_per_second: 100
    include_malformed: 0.05  # 5% malformed events

# Environment-specific overrides
environments:
  production:
    ingestion:
      log_level: "WARNING"
      max_events_per_file: 100000
      batch_size: 5000
    
    monitoring:
      prometheus:
        enabled: true
      alerts:
        error_rate_threshold: 0.01  # 1%
    
    security:
      encryption:
        enabled: true
      audit:
        enabled: true
  
  development:
    ingestion:
      log_level: "DEBUG"
      max_events_per_file: 1000
      batch_size: 100
    
    development:
      debug:
        enabled: true
        profile_performance: true
        verbose_errors: true
  
  testing:
    ingestion:
      log_level: "DEBUG"
      continue_on_parse_errors: false
    
    development:
      test_data:
        enabled: true
        generate_events: 100
        include_malformed: 0.20  # 20% for testing error handling

# External integrations
integrations:
  # Elasticsearch for log storage
  elasticsearch:
    enabled: false
    hosts:
      - "http://elasticsearch:9200"
    index_pattern: "siem-events-{tenant}-{date}"
    
  # Kafka for event streaming
  kafka:
    enabled: false
    bootstrap_servers:
      - "kafka:9092"
    topic_pattern: "siem.events.{tenant}"
    
  # S3 for long-term storage
  s3:
    enabled: false
    bucket: "siem-events-archive"
    prefix: "events/{tenant}/{year}/{month}/{day}/"
    
  # Webhook notifications
  webhooks:
    enabled: false
    endpoints:
      - url: "https://alerts.company.com/siem"
        events: ["error", "high_volume"]
        timeout: 10

# Resource limits and quotas
resource_limits:
  # Memory limits
  memory:
    max_heap_size_mb: 4096
    max_buffer_size_mb: 512
    gc_threshold: 0.80
  
  # CPU limits
  cpu:
    max_threads: 8
    thread_pool_size: 4
    cpu_threshold: 0.85
  
  # Disk limits
  disk:
    max_temp_space_gb: 10
    max_log_size_mb: 1024
    cleanup_interval_hours: 24
  
  # Network limits
  network:
    max_connections: 100
    connection_timeout: 30
    read_timeout: 60
    write_timeout: 30