#!/bin/bash

# Manual UI Testing Script
# This script provides a systematic approach to test all UI pages

echo "🔍 SIEM UI Comprehensive Testing"
echo "================================="
echo ""
echo "UI Server should be running on: http://localhost:3004/"
echo "API Server should be running on: http://localhost:8080/"
echo ""
echo "📋 Testing Checklist:"
echo ""

# Define all pages to test
pages=(
    "Dashboard:dashboard"
    "Alerts:alerts"
    "Cases:cases"
    "Admin:admin"
    "Rules:rules"
    "Log Sources:log-sources"
    "Users:users"
    "Parsers:parsers"
    "Interactive Parser:interactive-parser"
    "Events:events"
    "Log Activity:log-activity"
    "Vendor Mapping:vendor-mapping"
    "Agent Fleet:agent-fleet"
)

# Test each page
for page_info in "${pages[@]}"; do
    IFS=':' read -r page_name page_path <<< "$page_info"
    echo "📄 Testing: $page_name"
    echo "   Path: $page_path"
    echo "   ✓ Navigate to page in browser"
    echo "   ✓ Check for 404 errors"
    echo "   ✓ Check browser console for errors"
    echo "   ✓ Check network tab for failed API calls"
    echo "   ✓ Verify page content loads"
    echo "   ✓ Test interactive elements"
    echo ""
done

echo "🔧 API Endpoints to Test:"
echo ""
echo "Dashboard APIs:"
echo "  GET /api/v1/dashboard - Dashboard KPIs"
echo "  GET /api/v1/events/search - Events search"
echo ""
echo "Alerts APIs:"
echo "  GET /api/v1/alerts - List alerts"
echo "  GET /api/v1/alerts/{id} - Alert details"
echo "  PUT /api/v1/alerts/{id}/status - Update alert status"
echo ""
echo "Cases APIs:"
echo "  GET /api/v1/cases - List cases"
echo "  POST /api/v1/cases - Create case"
echo "  GET /api/v1/cases/{id} - Case details"
echo ""
echo "Rules APIs:"
echo "  GET /api/v1/rules - List rules"
echo "  POST /api/v1/rules - Create rule"
echo "  PUT /api/v1/rules/{id} - Update rule"
echo "  DELETE /api/v1/rules/{id} - Delete rule"
echo ""
echo "Log Sources APIs:"
echo "  GET /api/v1/log-sources - List log sources"
echo "  POST /api/v1/log-sources - Create log source"
echo ""
echo "Users APIs:"
echo "  GET /api/v1/users - List users"
echo "  POST /api/v1/users - Create user"
echo ""
echo "Parsers APIs:"
echo "  GET /api/v1/parsers - List parsers"
echo "  POST /api/v1/parsers - Create parser"
echo "  POST /api/v1/parsers/test - Test parser"
echo ""
echo "Agent Fleet APIs:"
echo "  GET /api/v1/agents - List agents"
echo "  GET /api/v1/agents/{id}/status - Agent status"
echo ""
echo "🧪 Quick API Tests:"
echo ""
echo "Testing Dashboard API..."
curl -s -o /dev/null -w "Dashboard API: %{http_code}\n" "http://localhost:8080/api/v1/dashboard"

echo "Testing Events Search API..."
curl -s -o /dev/null -w "Events Search API: %{http_code}\n" "http://localhost:8080/api/v1/events/search"

echo "Testing Alerts API..."
curl -s -o /dev/null -w "Alerts API: %{http_code}\n" "http://localhost:8080/api/v1/alerts"

echo "Testing Rules API..."
curl -s -o /dev/null -w "Rules API: %{http_code}\n" "http://localhost:8080/api/v1/rules"

echo "Testing Log Sources API..."
curl -s -o /dev/null -w "Log Sources API: %{http_code}\n" "http://localhost:8080/api/v1/log-sources"

echo "Testing Users API..."
curl -s -o /dev/null -w "Users API: %{http_code}\n" "http://localhost:8080/api/v1/users"

echo "Testing Parsers API..."
curl -s -o /dev/null -w "Parsers API: %{http_code}\n" "http://localhost:8080/api/v1/parsers"

echo "Testing Agents API..."
curl -s -o /dev/null -w "Agents API: %{http_code}\n" "http://localhost:8080/api/v1/agents"

echo ""
echo "✅ Manual Testing Instructions:"
echo ""
echo "1. Open browser to http://localhost:3004/"
echo "2. Open Developer Tools (F12)"
echo "3. Go to Console tab to monitor errors"
echo "4. Go to Network tab to monitor API calls"
echo "5. Navigate through each page using the sidebar"
echo "6. For each page:"
echo "   - Verify page loads without 404"
echo "   - Check console for JavaScript errors"
echo "   - Check network tab for failed API calls (red entries)"
echo "   - Verify page content displays correctly"
echo "   - Test interactive elements (buttons, forms, etc.)"
echo ""
echo "🚨 Common Issues to Look For:"
echo ""
echo "- 404 Not Found errors"
echo "- JavaScript console errors (red text)"
echo "- Failed API calls (red network requests)"
echo "- Empty or broken page content"
echo "- Non-functional buttons or forms"
echo "- Authentication/authorization errors"
echo "- CORS errors"
echo "- Timeout errors"
echo ""
echo "📊 Expected Results:"
echo ""
echo "✅ All pages should load successfully (no 404)"
echo "✅ No JavaScript console errors"
echo "✅ All API calls should return 200 or appropriate status codes"
echo "✅ Page content should display correctly"
echo "✅ Interactive elements should be functional"
echo ""
echo "Happy Testing! 🎯"