#!/usr/bin/env bash
# collector_wizard.sh - First-boot configuration wizard for edge collector
set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[wizard]${NC} $1"; }
info() { echo -e "${BLUE}[info]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }
error() { echo -e "${RED}[error]${NC} $1"; }

# Banner
clear
cat << 'EOF'
 _____ _____ ______ __  __    _____      _ _           _             
/  ___|_   _|  ____|  \/  |  / ____|    | | |         | |            
\ `--.  | | | |__  | .  . | | |     ___ | | | ___  ___| |_ ___  _ __ 
 `--. \ | | |  __| | |\/| | | |    / _ \| | |/ _ \/ __| __/ _ \| '__|
/\__/ /_| |_| |____| |  | | | |___| (_) | | |  __/ (__| || (_) | |   
\____/ \___/\______|_|  |_|  \_____\___/|_|_|\___|\___|\__\___/|_|   

                    Edge Collector Configuration Wizard
EOF

echo ""
log "Welcome to the SIEM Edge Collector setup wizard!"
echo ""

# Detect current network config
get_current_network() {
    if command -v ip >/dev/null 2>&1; then
        # Linux with iproute2
        IP=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -1)
        NETMASK=$(ip -4 addr show | grep "$IP" | awk '{print $2}' | cut -d'/' -f2)
        GW=$(ip route | grep default | awk '{print $3}' | head -1)
        DNS=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -1)
    elif command -v ifconfig >/dev/null 2>&1; then
        # macOS/BSD
        IP=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -1)
        NETMASK="24"  # Default assumption
        GW=$(netstat -nr | grep default | awk '{print $2}' | head -1)
        DNS=$(scutil --dns 2>/dev/null | grep nameserver | awk '{print $3}' | head -1 || echo "8.8.8.8")
    else
        # Fallback
        IP="192.168.1.100"
        NETMASK="24"
        GW="192.168.1.1"
        DNS="8.8.8.8"
    fi
}

# Get current config
get_current_network

info "Current network configuration detected:"
echo "  IP Address: $IP"
echo "  Netmask: /$NETMASK"
echo "  Gateway: $GW"
echo "  DNS: $DNS"
echo ""

# Interactive configuration
read -p "$(echo -e "${BLUE}Enter collector IP address${NC} [$IP]: ")" NEW_IP
NEW_IP=${NEW_IP:-$IP}

read -p "$(echo -e "${BLUE}Enter netmask (CIDR)${NC} [$NETMASK]: ")" NEW_NETMASK
NEW_NETMASK=${NEW_NETMASK:-$NETMASK}

read -p "$(echo -e "${BLUE}Enter gateway IP${NC} [$GW]: ")" NEW_GW
NEW_GW=${NEW_GW:-$GW}

read -p "$(echo -e "${BLUE}Enter DNS server${NC} [$DNS]: ")" NEW_DNS
NEW_DNS=${NEW_DNS:-$DNS}

echo ""
read -p "$(echo -e "${BLUE}Enter SIEM server URL${NC} [http://192.168.1.10:9999]: ")" SIEM_URL
SIEM_URL=${SIEM_URL:-"http://192.168.1.10:9999"}

read -p "$(echo -e "${BLUE}Enter tenant ID${NC} [1]: ")" TENANT_ID
TENANT_ID=${TENANT_ID:-1}

read -p "$(echo -e "${BLUE}Enter site tag${NC} [main-office]: ")" SITE_TAG
SITE_TAG=${SITE_TAG:-"main-office"}

# Generate configuration
CONFIG_DIR="/etc/siem-collector"
mkdir -p "$CONFIG_DIR"

log "Generating network configuration..."

# Network config (systemd-networkd style)
if [ -d "/etc/systemd/network" ]; then
    cat > "/etc/systemd/network/10-collector.network" <<EOF
[Match]
Name=eth0

[Network]
Address=$NEW_IP/$NEW_NETMASK
Gateway=$NEW_GW
DNS=$NEW_DNS

[DHCP]
UseDNS=false
EOF
    log "Created systemd network configuration"
fi

# Collector config
cat > "$CONFIG_DIR/collector.env" <<EOF
# SIEM Collector Configuration
# Generated by wizard on $(date)

# Network
COLLECTOR_IP=$NEW_IP

# SIEM Connection
SIEM_BASE_URL=$SIEM_URL
TENANT_ID=$TENANT_ID
SOURCE_ID=collector-$SITE_TAG-$(date +%s)
SITE_TAG=$SITE_TAG

# Features
INCLUDE_DEBUG=false
EOF

log "Created collector environment file"

# Generate QR code for enrollment (if qrencode available)
ENROLL_URL="$SIEM_URL/enroll?collector=$NEW_IP&site=$SITE_TAG"
if command -v qrencode >/dev/null 2>&1; then
    log "Generating enrollment QR code..."
    qrencode -t UTF8 "$ENROLL_URL"
    echo ""
    info "Scan this QR code from the SIEM console to complete enrollment"
else
    info "Enrollment URL: $ENROLL_URL"
fi

# Summary
echo ""
log "Configuration complete!"
echo ""
info "Network configuration:"
echo "  IP: $NEW_IP/$NEW_NETMASK"
echo "  Gateway: $NEW_GW"
echo "  DNS: $NEW_DNS"
echo ""
info "SIEM configuration:"
echo "  Server: $SIEM_URL"
echo "  Tenant: $TENANT_ID"
echo "  Site: $SITE_TAG"
echo ""
info "Health check URL:"
echo "  http://$NEW_IP:8515/health"
echo ""

# Apply configuration
read -p "$(echo -e "${YELLOW}Apply configuration and restart services?${NC} [Y/n]: ")" APPLY
APPLY=${APPLY:-Y}

if [[ "$APPLY" =~ ^[Yy]$ ]]; then
    log "Applying configuration..."
    
    # Restart networking
    if systemctl is-active systemd-networkd >/dev/null 2>&1; then
        systemctl restart systemd-networkd
    fi
    
    # Start collector service
    if [ -f "/etc/systemd/system/siem-collector.service" ]; then
        systemctl daemon-reload
        systemctl enable siem-collector
        systemctl restart siem-collector
        log "Collector service started"
    else
        warn "Collector service not found. Please start manually."
    fi
    
    # Wait for service
    sleep 2
    
    # Check health
    if curl -fsS "http://127.0.0.1:8515/health" >/dev/null 2>&1; then
        log "✓ Collector is healthy!"
    else
        warn "Collector health check failed. Check logs: journalctl -u siem-collector"
    fi
else
    info "Configuration saved but not applied. Apply manually when ready."
fi

log "Wizard complete!"
