#!/usr/bin/env bash
set -e

echo "Creating synthetic test data for empty rule files..."

# Create synthetic events for rules that had no matching data
cat > testdata/rule-event_action_empty.json << 'EOF'
{"event_id":"synth-action-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"test","raw_event":"synthetic event with empty action","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
{"event_id":"synth-action-02","tenant_id":"test-tenant","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"test","raw_event":"synthetic event 2 with empty action","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

cat > testdata/rule-event_category_test_volume.json << 'EOF'
{"event_id":"synth-test-cat-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"test","raw_event":"synthetic event with test category","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

cat > testdata/rule-event_outcome_empty.json << 'EOF'
{"event_id":"synth-outcome-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"test","raw_event":"synthetic event with empty outcome","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

cat > testdata/rule-ingestion_timestamp_zero.json << 'EOF'
{"event_id":"synth-ingest-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":0,"source_ip":"","source_type":"test","raw_event":"synthetic event with zero ingestion timestamp","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

cat > testdata/rule-multi_field_correlation.json << 'EOF'
{"event_id":"synth-multi-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"Unknown","raw_event":"synthetic event for multi-field correlation","event_category":"Unknown","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

cat > testdata/rule-source_type_test_volume.json << 'EOF'
{"event_id":"synth-src-test-01","tenant_id":"tenant-A","event_timestamp":0,"ingestion_timestamp":1733450000,"source_ip":"","source_type":"test","raw_event":"synthetic event with test source type","event_category":"test","event_outcome":"","event_action":"","is_threat":0,"value":null,"hour":null,"log_source_id":null,"parse_error_msg":null,"parsing_status":"success","alert_id":null,"alerts":null,"user":null,"src_user":null,"dest_user":null,"user_type":null,"dest_ip":null,"src_port":null,"dest_port":null,"protocol":null,"bytes_in":null,"bytes_out":null,"packets_in":null,"packets_out":null,"duration":null,"transport":null,"direction":null,"process_name":null,"parent_process":null,"process_id":null,"parent_process_id":null,"file_hash":null,"file_path":null,"file_name":null,"file_size":null,"command_line":null,"registry_key":null,"registry_value":null,"url":null,"uri_path":null,"uri_query":null,"http_method":null,"http_status_code":null,"http_user_agent":null,"http_referrer":null,"http_content_type":null,"http_content_length":null,"src_host":null,"dest_host":null,"device_type":null,"vendor":null,"product":null,"version":null,"src_country":null,"dest_country":null,"src_zone":null,"dest_zone":null,"interface_in":null,"interface_out":null,"vlan_id":null,"rule_id":null,"rule_name":null,"policy_id":null,"policy_name":null,"signature_id":null,"signature_name":null,"threat_name":null,"threat_category":null,"severity":null,"priority":null,"auth_method":null,"auth_app":null,"failure_reason":null,"session_id":null,"app_name":null,"app_category":null,"service_name":null,"email_sender":null,"email_recipient":null,"email_subject":null,"tags":null,"message":null,"details":null,"custom_fields":{}}
EOF

echo "Created synthetic test data for previously empty rule files."
echo "Final verification:"

# Final count check
for f in testdata/rule-*.json; do
    lines=$(wc -l < "$f")
    if [ "$lines" -eq 0 ]; then
        echo "ERROR: $f is still empty"
    else
        echo "$(basename "$f"): $lines events ✓"
    fi
done | wc -l

echo "Total rule test files: $(ls testdata/rule-*.json | wc -l)"