version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports: ["8123:8123", "9000:9000"]
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123/ping"]
      interval: 5s
      retries: 20

  kafka:
    image: bitnami/kafka:3.7
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
    ports: ["9092:9092"]
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      retries: 30