ATTACH TABLE _ UUID '51dfbaaf-51bd-4d67-955c-c8559eb3d7d5'
(
    `event_id` String,
    `tenant_id` String,
    `raw_event` String,
    `parsing_status` String,
    `parse_error_msg` Nullable(String),
    `timestamp` UInt64,
    `ingestion_time` UInt64,
    `level` String,
    `message` String,
    `source` Nullable(String),
    `source_ip` Nullable(String),
    `dest_ip` Nullable(String),
    `source_port` Nullable(UInt16),
    `dest_port` Nullable(UInt16),
    `protocol` Nullable(String),
    `action` Nullable(String),
    `result` Nullable(String),
    `user_name` Nullable(String),
    `user_id` Nullable(String),
    `user_domain` Nullable(String),
    `user_category` Nullable(String),
    `process_name` Nullable(String),
    `process_id` Nullable(UInt32),
    `process_path` Nullable(String),
    `parent_process_name` Nullable(String),
    `parent_process_id` Nullable(UInt32),
    `file_name` Nullable(String),
    `file_path` Nullable(String),
    `file_hash` Nullable(String),
    `file_size` Nullable(UInt64),
    `url` Nullable(String),
    `http_method` Nullable(String),
    `http_status` Nullable(UInt16),
    `user_agent` Nullable(String),
    `referer` Nullable(String),
    `host_name` Nullable(String),
    `os` Nullable(String),
    `severity` Nullable(String),
    `category` Nullable(String),
    `vendor` Nullable(String),
    `product` Nullable(String),
    `version` Nullable(String),
    `custom_fields` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(toDateTime(timestamp / 1000))
ORDER BY (tenant_id, timestamp, event_id)
SETTINGS index_granularity = 8192
