name: siem-rust-lint
on:
  pull_request:
  push:
    branches: [ main, feat/** ]
jobs:
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Lint & Test
        run: |
          chmod +x scripts/ci/rust_lint.sh
          scripts/ci/rust_lint.sh

